server:
  port: 10010
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/ZMS_USR?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: 06494784
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            spl: trace
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

jwt:
  secret: test
  expiration: 3600