server:
  port: 10010
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/ZMS_USR?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: root
    password: 06494784
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  cloud:
#    gateway:
#      routes:
#        - id: user-service # router identification -> unique
#          uri: lb://user-service # router target
#          predicates: # request whether match the rule of route
#            - Path=/user/** # verify the request whether start with this path or not
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.openfeign: DEBUG
    org:
      hibernate:
        type:
          descriptor:
            spl: trace
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

jwt:
  secret: test
  expiration: 3600